services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        value: your-actual-key-or-use-secret
      - key: DATABASE_URL
        fromDatabase:
          name: research_doc
          property: connectionString
    disks:
      - name: embedding-disk
        mountPath: /var/data/embedding_store
        sizeGB: 1

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 10001
    envVars:
      - key: BACKEND_URL
        value: https://fastapi-backend.onrender.com
