services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    repo: https://github.com/hemantkumarlearning/hemant-kumar-wasserstoff-AiInternTask
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        value: your-actual-key-or-use-secret
      - key: OPENAI_API_KEY
        value: your-actual-key-or-use-secret
      - key: DATABASE_URL
        value: postgresql://doc_user:7R31q2a1RY4k9vzBJfRZVMz4InM3bIZz@dpg-d0llu9adbo4c73apjr40-a/research_doc

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    repo: https://github.com/hemantkumarlearning/hemant-kumar-wasserstoff-AiInternTask
    branch: main
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 10001
    envVars:
      - key: BACKEND_URL
        value: https://fastapi-backend.onrender.com
